const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM', 
    REMOVE_ITEM: 'REMOVE_ITEM', 
    EMPTY_ITEM_FROM_CART: 'EMPTY_ITEM_FROM_CART',
    EMPTY_CART: 'EMPTY_CART' 
}

export default CartActionTypes